version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH $CIRCLE_PULL_REQUEST

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install node and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version && npm -v

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-my-project-{{ checksum "package-lock.json" }}

      - run:
          name: Install SLS Plugins
          command: sls plugin install -n serverless-wsgi serverless-python-requirements

      - run:
          name: Deploy application
          command: sls deploy --stage master

  deploy_integration:
    docker:
      - image: circleci/python3.7
    working_directory: /tmp/trace
    steps:
      - run:
          name: Deploy if tests pass and branch is integration
          command: sls deploy --stage integration --user $DB_USERNAME --pass $DB_PASSWORD

  deploy_master:
    docker:
      - image: circleci/python3.7
    working_directory: /tmp/trace
    steps:
      - run:
          name: Deploy if tests pass and branch is master
          command: sls deploy --stage master --user $DB_USERNAME --pass $DB_PASSWORD

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy_integration:
          requires:
            - build
          filters:
            branches:
              only: integration
      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only: master

